name: recipe-apax-base
recipe: drupal11
config:
  php: '8.3'
  via: apache:2.4
  database: mysql:8.0
  webroot: web
  composer_version: 2-latest

services:
  appserver:
    environment:
      DRUSH_OPTIONS_URI: https://recipe-apax-base.lndo.site
