name: 'Drupal Base'
description: 'Core modules and configuration for a new Drupal 10 project.'
type: 'Site'

input:
  site_name:
    data_type: string
    description: 'The name of the site.'
    constraints:
      NotBlank: []
    prompt:
      method: ask
      arguments:
        question: 'What is the name of your site?'
    default:
      source: value
      value: 'My Drupal Site'
  site_mail:
    data_type: string
    description: 'The email address for the site.'
    constraints:
      NotBlank: []
      Email: []
    prompt:
      method: ask
      arguments:
        question: 'What is the site email address?'
    default:
      source: value
      value: 'admin@example.com'
  site_slogan:
    data_type: string
    description: 'The slogan for the site.'
    prompt:
      method: ask
      arguments:
        question: 'What is the site slogan? (optional)'
    default:
      source: value
      value: ''

install:
  - automated_cron
  - big_pipe
  - block
  - block_content
  - ckeditor5
  - claro
  - config
  - contextual
  - datetime
  - dblog
  - dynamic_page_cache
  - field_ui
  - editor
  - filter
  - image
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - options
  - path
  - redirect
  - serialization
  - taxonomy
  - text
  - toolbar
  - user
  - views
  - views_ui
  - admin_toolbar
  - admin_toolbar_tools
  - better_permissions_page
  - coffee
  - config_ignore
  - config_split
  - easy_responsive_images
  - exif_orientation
  - focal_point
  - gin
  - gin_login
  - gin_toolbar
  - imageapi_optimize_webp
  - maxlength
  - pathauto
  - publication_date

config:
  import:
    dblog: '*'
    image:
      - image.style.thumbnail
      - image.style.media_library
      - image.style.responsive_650w
      - image.style.responsive_950w
      - image.style.responsive_1250w
      - image.style.responsive_1550w
      - image.style.responsive_1850w
      - image.style.responsive_2150w
      - image.style.responsive_1_1_650w
      - image.style.responsive_1_1_950w
      - image.style.responsive_1_1_1250w
      - image.style.responsive_1_1_1550w
      - image.style.responsive_1_1_1850w
      - image.style.responsive_1_1_2150w
      - image.style.responsive_4_3_650w
      - image.style.responsive_4_3_950w
      - image.style.responsive_4_3_1250w
      - image.style.responsive_4_3_1550w
      - image.style.responsive_4_3_1850w
      - image.style.responsive_4_3_2150w
    easy_responsive_images: '*'
    media: '*'
    media_library: '*'
    pathauto: '*'
    redirect:
      - redirect.settings
      - system.action.redirect_delete_action
      - views.view.redirect
    node:
      - views.view.content
    user:
      - views.view.user_admin_people
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
      - block.block.gin_secondary_local_tasks
    config_split:
      - config_split.config_split.local
    admin_toolbar:
      - admin_toolbar.settings
    admin_toolbar_tools:
      - admin_toolbar_tools.settings
    coffee:
      - coffee.configuration
    gin_login:
      - gin_login.settings
    focal_point:
      - focal_point.settings
    crop:
      - crop.settings
      - crop.type.focal_point
    system:
      - system.action.pathauto_update_alias_node
  actions:
    system.site:
      simple_config_update:
        name: ${site_name}
        mail: ${site_mail}
        slogan: ${site_slogan}
    system.theme:
      simple_config_update:
        admin: 'gin'
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
    node.settings:
      simple_config_update:
        use_admin_theme: true
    user.settings:
      simple_config_update:
        register: admin_only
    automated_cron.settings:
      simple_config_update:
        interval: 0
