name: 'Apax Base Drupal Recipe'
description: 'Core modules and configuration for a new Drupal 11 project.'
type: 'Site'

input:
  site_name:
    data_type: string
    description: 'The name of the site.'
    constraints:
      NotBlank: []
    prompt:
      method: ask
      arguments:
        question: 'What is the name of your site?'
    default:
      source: value
      value: 'My Drupal Site'
  site_mail:
    data_type: string
    description: 'The email address for the site.'
    constraints:
      NotBlank: []
      Email: []
    prompt:
      method: ask
      arguments:
        question: 'What is the site email address?'
    default:
      source: value
      value: 'admin@example.com'
  site_slogan:
    data_type: string
    description: 'The slogan for the site.'
    prompt:
      method: ask
      arguments:
        question: 'What is the site slogan? (optional)'
    default:
      source: value
      value: ''

recipes:
  - core/recipes/page_content_type
  - core/recipes/image_media_type
  - core/recipes/standard_responsive_images
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  - core/recipes/administrator_role
  - core/recipes/content_editor_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance

install:
  # Core
  - block_content
  - config
  - contextual
  - datetime
  - datetime_range
  - entity_reference_revisions
  - field_ui
  - help
  - menu_link_content
  - menu_ui
  - options
  - taxonomy
  - update
  - views_ui
  # Contrib
  - admin_toolbar
  - admin_toolbar_tools
  - better_permissions_page
  - ckeditor5_plugin_pack
  - ckeditor5_plugin_pack_font
  - ckeditor5_plugin_pack_fullscreen
  - ckeditor5_plugin_pack_highlight
  - ckeditor5_plugin_pack_indent_block
  - ckeditor5_plugin_pack_page_break
  - ckeditor5_plugin_pack_paste_markdown
  - ckeditor5_plugin_pack_templates
  - ckeditor5_plugin_pack_text_transformation
  - coffee
  - config_ignore
  - config_split
  - easy_responsive_images
  - exif_orientation
  - focal_point
  - fontawesome
  - gin
  - gin_login
  - gin_toolbar
  - imageapi_optimize_webp
  - maxlength
  - metatag
  - paragraphs
  - pathauto
  - publication_date
  - redirect
  - webform
  - webform_submission_export_import
  - webform_ui

config:
  strict:
    - field.storage.node.field_components
    - field.storage.paragraph.field_html
  import:
    # -- Core Modules -- #
    block_content:
      - views.view.block_content
    menu_ui: '*'
    node:
      # We only want a subset of the node imports from the page_content_type recipe.
      - field.storage.node.body
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
      - views.view.content
    user:
      - views.view.user_admin_people

    # -- Contrib Modules -- #
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    better_permissions_page: '*'
    ckeditor5_plugin_pack: '*'
    coffee: '*'
    config_ignore: '*'
    config_split: '*'
    easy_responsive_images: '*'
    exif_orientation: '*'
    focal_point: '*'
    fontawesome: '*'
    gin: '*'
    gin_login: '*'
    gin_toolbar: '*'
    imageapi_optimize_webp: '*'
    maxlength: '*'
    metatag: '*'
    paragraphs: '*'
    pathauto: '*'
    publication_date: '*'
    redirect: '*'
    webform: '*'

  actions:
    # Set the default timezone.
    system.date:
      simpleConfigUpdate:
        timezone.default: America/New_York
        timezone.user.configurable: false
    # Set the site name, email, and slogan.
    system.site:
      simpleConfigUpdate:
        name: ${site_name}
        mail: ${site_mail}
        slogan: ${site_slogan}
    # Set the admin theme to gin.
    system.theme:
      simpleConfigUpdate:
        admin: 'gin'
        default: 'gin'
    # Set the node settings to use the admin theme.
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    # Users can only be created by an admin.
    user.settings:
      simpleConfigUpdate:
        register: admin_only
    # Show local tasks in the admin toolbar.
    admin_toolbar_tools.settings:
      simpleConfigUpdate:
        show_local_tasks: true

    # Configure gin theme settings.
    gin.settings:
      simpleConfigUpdate:
        enable_darkmode: '0'
        classic_toolbar: vertical
        sticky_action_buttons: true
        features.node_user_picture: true

    # Page content type: form display - hide body, add components.
    core.entity_form_display.node.page.default:
      hideComponent: body
      setComponents:
        - name: field_components
          options:
            type: paragraphs
            weight: 121
            region: content
            settings:
              title: Paragraph
              title_plural: Paragraphs
              edit_mode: open
              closed_mode: summary
              autocollapse: none
              closed_mode_threshold: 0
              add_mode: dropdown
              form_display_mode: default
              default_paragraph_type: _none
              features:
                add_above: '0'
                collapse_edit_all: collapse_edit_all
                convert: '0'
                duplicate: duplicate
            third_party_settings: {  }
        - name: published_at
          options:
            type: publication_date_timestamp
            weight: 10
            region: content
            settings: {  }
            third_party_settings: {  }
        - name: url_redirects
          options:
            weight: 50
            region: content
            settings: {  }
            third_party_settings: {  }

    # Page content type: view display - hide body, add components.
    core.entity_view_display.node.page.default:
      hideComponents:
        - body
        - published_at
      setComponent:
        name: field_components
        options:
          type: entity_reference_revisions_entity_view
          label: above
          settings:
            view_mode: default
            link: ''
          third_party_settings: {  }
          weight: 102
          region: content

    # Page content type: teaser display - hide body, components, published_at.
    core.entity_view_display.node.page.teaser:
      hideComponents:
        - body
        - field_components
        - published_at

    # Configure gin block placements.
    block.block.gin_content:
      simpleConfigUpdate:
        weight: -3
    block.block.gin_local_actions:
      simpleConfigUpdate:
        weight: -4
    block.block.gin_page_title:
      simpleConfigUpdate:
        region: header
        weight: -3
    block.block.gin_primary_local_tasks:
      simpleConfigUpdate:
        weight: -2

    # Disable unwanted gin blocks.
    block.block.gin_admin:
      simpleConfigUpdate:
        status: false
    block.block.gin_branding:
      simpleConfigUpdate:
        status: false
    block.block.gin_local_tasks:
      simpleConfigUpdate:
        status: false
    block.block.gin_tools:
      simpleConfigUpdate:
        status: false

    # Set up user roles and permissions.
    user.role.anonymous:
      setProperties:
        weight: -10
      grantPermission: 'access content'
    user.role.administrator:
      setProperties:
        weight: 10
    user.role.authenticated:
      grantPermissions:
        - 'access content'
        - 'delete own files'
        - 'view own unpublished content'
    user.role.content_editor:
      grantPermissions:
        - 'access content overview'
        - 'access contextual links'
        - 'access files overview'
        - 'access toolbar'
        - 'access webform overview'
        - 'access webform submission user'
        - 'administer taxonomy'
        - 'administer url aliases'
        - 'create terms in tags'
        - 'create url aliases'
        - 'delete own files'
        - 'delete terms in tags'
        - 'edit terms in tags'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view own webform submission'
        - 'view the administration theme'
      grantPermissionsForEachNodeType:
        - 'create %bundle content'
        - 'delete %bundle revisions'
        - 'delete own %bundle content'
        - 'edit own %bundle content'
